name: tanks_battel_server
description: A server app using the shelf package and Docker.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.1 <3.0.0'

dependencies:
  json_annotation: ^4.8.0
  json_serializable: ^6.4.1
  args: ^2.3.0
  shelf: ^1.4.0
  shelf_router: ^1.1.0
  shelf_static: ^1.1.1
  shelf_web_socket: ^1.0.3
  web_socket_channel: ^2.3.0
  event_bus_arch: ^1.3.0+8
  equatable: ^2.0.5

dev_dependencies:
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.21.0
  build_runner: ^2.2.0